[project]
name = "nft-nyc-exclusive"
costs_version = 1

[contracts.nft-trait]
depends_on = []
path = "contracts/nft-trait.clar"

[contracts.nft-nyc-exclusive]
depends_on = ["nft-trait"]
path = "contracts/nft-nyc-exclusive.clar"